#!/bin/bash
set -e

# ==================================================================================================
# Start the nginx server
# ==================================================================================================
service nginx start


# ==================================================================================================
# Generate the template(s)
# ==================================================================================================
CONSUL_URL=${CONSUL_URL:-example.com:8500}
CONFIG_CMD=${CONFIG_CMD:-service nginx reload}

CONFIG_SRC=${CONSUL_SRC:-/etc/nginx/conf.d/templates/nginx.conf.ctmpl}
CONFIG_DST=${CONSUL_DST:-/etc/nginx/conf.d/nginx.conf}
consul-template -consul-addr=$CONSUL_URL -template="${CONFIG_SRC}:${CONFIG_DST}:${CONFIG_CMD}"

# TODO: Split template definition in two parts
#LOCATION_SRC=${CONSUL_SRC:-/etc/nginx/conf.d/templates/locations.conf.ctmpl}
#LOCATION_DST=${CONSUL_DST:-/etc/nginx/conf.d/locations/proxy.conf}
#consul-template -consul-addr=$CONSUL_URL -template="${LOCATION_SRC}:${LOCATION_DST}:${CONFIG_CMD}"

# TODO: Split template definition in two parts
#UPSTREAM_SRC=${CONSUL_SRC:-/etc/nginx/conf.d/templates/upstreams.conf.ctmpl}
#UPSTREAM_DST=${CONSUL_DST:-/etc/nginx/conf.d/upstreams/proxy.conf}
#consul-template -consul-addr=$CONSUL_URL -template="${UPSTREAM_SRC}:${UPSTREAM_DST}:${CONFIG_CMD}"
