# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define :devops do |devops|
    devops.vm.network "private_network", ip: "10.100.199.200"
    devops.vm.provision :shell, path: "./ansible/install"
    devops.vm.provision :shell, inline: 'ls -la /vagrant/'
    devops.vm.provision :shell,
      inline: 'PYTHONUNBUFFERED=1 ansible-playbook \
        /vagrant/ansible/docker.yml -c local'
  end

  config.vm.define :prod do |prod|
    prod.vm.network "private_network", ip: "10.100.199.100"
    prod.vm.provision :shell, path: "./ansible/install"
    prod.vm.provision :shell, inline: 'ls -la /vagrant/'
    prod.vm.provision :shell,
      inline: 'PYTHONUNBUFFERED=1 ansible-playbook \
        /vagrant/ansible/docker.yml -c local'
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_install = true
    config.vbguest.no_remote = true
  end
end
