#!/bin/bash
source .env

TARGET_NAME=${1:-}

if [ ! "${TARGET_NAME}" == "" ]
then
    echo "Building image: ${TARGET_NAME}..."
    docker build -t "${TARGET_REPO}/${TARGET_NAME}:latest" "${TARGET_NAME}"
    echo "Done."
else
    echo "Building component images..."
    scan_dir="./components/"
    find "${scan_dir}" -name "Dockerfile" -print0 |
    while IFS= read -r -d $'\0' tag; do
        tag=${tag#${scan_dir}/}
        tag=${tag%/Dockerfile}
        docker build -t "${TARGET_REPO}/${tag}:latest" "${scan_dir}${tag}"
    done

    echo "Building sources..."
    scan_dir="./src/"
    find "${scan_dir}" -name "Dockerfile" -print0 |
    while IFS= read -r -d $'\0' tag; do
        tag=${tag#${scan_dir}/}
        tag=${tag%/Dockerfile}
        docker build -t "${TARGET_REPO}/${tag}:latest" "${scan_dir}${tag}"
    done

    echo "Done."
fi

echo "Listing domain-specific images..."
echo ----------------------------------------------------------------------------------------------
docker images | sort | grep "${TARGET_REPO}"
echo ----------------------------------------------------------------------------------------------