#!/bin/bash
source .env

TARGET_NAME=${1:-}
TARGET_TAGS=${2:-latest}

if [ ! "${TARGET_NAME}" == "" ] && [ ! "${TARGET_NAME}" == "." ]
then
    echo "Building image: ${TARGET_NAME}..."
    docker push "${TARGET_REPO}/${TARGET_NAME}:${TARGET_TAGS}"
    echo "Done."
else
    echo "Publishing all images..."
    docker images | grep example.com | cut -d " " -f 1 |\
    while IFS= read -r src; do
        tag=${src}
        tag=${tag#${TARGET_REPO}/}
        echo + ${TARGET_REPO}/${tag}:latest
        docker push "${TARGET_REPO}/${tag}:${TARGET_TAGS}" #> /dev/null
    done

    echo "Done."
fi