#!/bin/bash

TARGET_NAME=${1:-}

if [ ! "${TARGET_NAME}" == "" ]
then
    echo "Building image: ${TARGET_NAME}..."
    docker push "example.com:5000/${TARGET_NAME}"
    echo "Done."
else
    echo "Building all images..."

    docker push "example.com:5000/proxy/http:latest"
    docker push "example.com:5000/proxy/https:latest"

    docker push "example.com:5000/src/tests/python/app:latest"
    docker push "example.com:5000/src/tests/python/redis:latest"

    docker push "example.com:5000/devops/portainer/app:latest"
    docker push "example.com:5000/devops/portainer/templates:latest"

    echo "Done."
fi