FROM steveltn/https-portal:1.0.0

#COPY config/example.com.conf.erb /var/lib/nginx-conf/example.com.conf.erb
#COPY config/example.com.ssl.conf.erb /var/lib/nginx-conf/example.com.ssl.conf.erb

# Info: To extend and include more custom configs...
# https://github.com/SteveLTN/https-portal

