#!/bin/bash
set -e

# Set defaults
CONSUL_URL=${CONSUL_URL:-consul:8500}

CONFIG_SRC=${CONSUL_SRC:-config/templates/nginx.conf.ctmpl}
CONFIG_DST=${CONSUL_DST:-config/nginx.conf.test}

# Generate the template(s)
consul-template -consul=$CONSUL_URL -template="${CONFIG_SRC}:${CONFIG_DST}" --once
