#!/bin/bash
set -e

# Set defaults
CONSUL_URL=${CONSUL_URL:-consul:8500}

UPSTREAM_SRC=${CONSUL_SRC:-config/templates/upstreams.conf.ctmpl}
UPSTREAM_DST=${CONSUL_DST:-config/upstreams/proxy.conf}

LOCATION_SRC=${CONSUL_SRC:-config/templates/locations.conf.ctmpl}
LOCATION_DST=${CONSUL_DST:-config/locations/proxy.conf}

# Generate the template(s)
consul-template -consul=$CONSUL_URL -template="${UPSTREAM_SRC}:${UPSTREAM_DST}" --once
consul-template -consul=$CONSUL_URL -template="${LOCATION_SRC}:${LOCATION_DST}" --once
