version: '2'
services:
  test-py:
    image: "example.com:5000/test-py:latest"
    environment:
     - TEST_STORAGE_REDIS=test-py-db
     - SERVICE_NAME=test-py
     - SERVICE_TAGS=app,test
     #- SERVICE_TAGS=app:5000/tests/python,test
    ports:
      - "5000"
    volumes:
     - ./src:/src

  test-py-db:
    image: "example.com:5000/redis:latest"
    environment:
     - SERVICE_NAME=test-py-db
     - SERVICE_TAGS=db,test
